import json, requests, pandas, openai

API_KEY = "API_KEY"
API_ENDPOINT = "https://api.openai.com/v1/chat/completions"

def generate_chat_completion(messages, model="gpt-4", temperature=1, max_tokens = None):
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {API_KEY}",
    }

    data = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
    }

    if max_tokens is not None:
        data["max_tokens"] = max_tokens

    response = requests.post(API_ENDPOINT, headers=headers, data=json.dumps(data))

    if response.status_code == 200:
        return response.json()["choices"][0]["message"]["content"]
    else:
        raise Exception(f"Error {response.status_code}: {response.text}")
    
messages = [
    {"role": "system", "content": "You are a helpful assistant and mentor for new graduates for employment."},
    {"role": "user", "content": "I have an important task for you. I'm providing you with job postings and I'd like you to analyze them. Here's the data format: Each job has a Job ID, Position, Required Skills, Benefits, and a Yearly Salary Range. Your task is to identify the most suitable ones for a new graduate and provide reasoning for your choice."},
    {"role": "system", "content": "Understood. Could you please provide an example job posting in the format you've described?"},
    {"role": "user", "content": "Sure. Here's an example: Job ID: 1, Position: Software Engineer, Required Skills: Proficiency in Java, C++, and Python; knowledge of web development frameworks; problem-solving abilities, Benefits: Flexible working hours, health insurance, retirement plans, professional development opportunities, Salary Range: $85,000 - $100,000."},
    {"role": "system", "content": "Got it. Now, could you provide an example of the output you'd like to see? This will help me better understand how to approach the task."},
    {"role": "user", "content": "Of course. Here's an example output: ID: 1 - REASONING: This job posting is suitable for a new graduate because it only asks for a passionate and eager-to-learn person. It does not list many technical skills as a requirement. That’s why it can be okay for a new graduate to apply for this job."},
    {"role": "system", "content": "Thank you for the example. I understand the task now. Are you ready to provide the job postings for analysis?"},
    {"role": "user", "content": "Yes, I'm ready. I will now give you 70 job postings. I want you to evaluate these jobs and find the best 7 ones for a new graduate. Please provide your output in the format you've seen in the example."},
    {"role": "user", "content": "Job ID: 2, Position: Marketing Coordinator, Required Skills: Excellent written and verbal communication, social media management, market research, Benefits: Paid time off, company-sponsored events, health and wellness programs, Salary Range: $45,000 - $55,000."},
    {"role": "user", "content": "Job ID: 3, Position: Graphic Designer, Required Skills: Proficiency in Adobe Creative Suite, strong visual design skills, attention to detail, Benefits: Remote work options, flexible schedule, annual bonus, Salary Range: $60,000 - $75,000."},
    {"role": "user", "content": "Job ID: 4, Position: Financial Analyst, Required Skills: Advanced Excel skills, financial modeling, data analysis, Benefits: 401(k) matching, tuition reimbursement, employee stock purchase plan, Salary Range: $70,000 - $85,000."},
    {"role": "user", "content": "Job ID: 5, Position: Registered Nurse, Required Skills: Nursing degree, valid state license, strong clinical skills, Benefits: Comprehensive healthcare coverage, retirement plans, paid parental leave, Salary Range: $65,000 - $80,000."},
    {"role": "user", "content": "Job ID: 6, Position: Sales Representative, Required Skills: Excellent communication skills, persuasive abilities, customer relationship management, Benefits: Uncapped commission, company car, annual sales incentive trips, Salary Range: $50,000 - $70,000."},
    {"role": "user", "content": "Job ID: 7, Position: Data Scientist, Required Skills: Proficiency in Python or R, machine learning techniques, statistical analysis, Benefits: Remote work options, flexible schedule, competitive bonus structure, Salary Range: $90,000 - $110,000."},
    {"role": "user", "content": "Job ID: 8, Position: Customer Service Representative, Required Skills: Strong interpersonal skills, problem-solving abilities, multitasking, Benefits: Paid training, employee discounts, career advancement opportunities, Salary Range: $30,000 - $40,000."},
    {"role": "user", "content": "Job ID: 9, Position: Human Resources Manager, Required Skills: Knowledge of labor laws, employee relations, talent acquisition, Benefits: Generous paid time off, employee assistance program, professional development budget, Salary Range: $80,000 - $95,000."},
    {"role": "user", "content": "Job ID: 10, Position: Electrician, Required Skills: Electrical knowledge, troubleshooting skills, ability to read blueprints, Benefits: Competitive pay, retirement plans, company vehicle, Salary Range: $50,000 - $65,000."},
    {"role": "user", "content": "Job ID: 11, Position: Software Architect, Required Skills: Strong software design skills, experience with system architecture, leadership abilities, Benefits: Remote work options, flexible hours, annual performance bonuses, Salary Range: $120,000 - $140,000."},
    {"role": "user", "content": "Job ID: 12, Position: Content Writer, Required Skills: Excellent writing skills, SEO knowledge, ability to meet deadlines, Benefits: Work-from-home options, flexible schedule, creative work environment, Salary Range: $40,000 - $50,000."},
    {"role": "user", "content": "Job ID: 13, Position: Mechanical Engineer, Required Skills: Proficiency in CAD software, problem-solving abilities, knowledge of thermodynamics, Benefits: Health insurance, retirement plans, professional development opportunities, Salary Range: $75,000 - $90,000."},
    {"role": "user", "content": "Job ID: 14, Position: Operations Manager, Required Skills: Leadership abilities, process improvement, supply chain management, Benefits: Competitive salary, performance-based bonuses, paid vacation, Salary Range: $90,000 - $110,000."},
    {"role": "user", "content": "Job ID: 15, Position: Social Media Manager, Required Skills: Experience with social media platforms, content creation, analytics, Benefits: Remote work options, flexible hours, company-sponsored training, Salary Range: $55,000 - $65,000."},
    {"role": "user", "content": "Job ID: 16, Position: Project Coordinator, Required Skills: Organizational skills, attention to detail, ability to manage timelines, Benefits: Paid time off, healthcare coverage, retirement plans, Salary Range: $45,000 - $55,000."},
    {"role": "user", "content": "Job ID: 17, Position: Legal Assistant, Required Skills: Knowledge of legal procedures, strong research skills, organizational abilities, Benefits: Competitive compensation, professional development support, generous holiday schedule, Salary Range: $40,000 - $50,000."},
    {"role": "user", "content": "Job ID: 18, Position: Biomedical Scientist, Required Skills: Laboratory research experience, data analysis, knowledge of medical terminology, Benefits: Health insurance, retirement plans, paid time off, Salary Range: $70,000 - $85,000."},
    {"role": "user", "content": "Job ID: 19, Position: Quality Assurance Engineer, Required Skills: Testing methodologies, attention to detail, knowledge of software development lifecycle, Benefits: Remote work options, flexible schedule, annual performance bonuses, Salary Range: $75,000 - $90,000."},
    {"role": "user", "content": "Job ID: 20, Position: Executive Assistant, Required Skills: Strong organizational skills, discretion, ability to manage multiple priorities, Benefits: Competitive salary, health and dental insurance, retirement plans, Salary Range: $55,000 - $70,000."},
    {"role": "user", "content": "Job ID: 21, Position: Mechanical Technician, Required Skills: Technical knowledge, troubleshooting abilities, familiarity with engineering drawings, Benefits: Paid time off, retirement plans, career advancement opportunities, Salary Range: $40,000 - $50,000."},
    {"role": "user", "content": "Job ID: 22, Position: Financial Controller, Required Skills: Financial analysis, budgeting and forecasting, knowledge of accounting principles, Benefits: Comprehensive healthcare coverage, retirement plans, annual bonuses, Salary Range: $100,000 - $120,000."},
    {"role": "user", "content": "Job ID: 23, Position: IT Support Specialist, Required Skills: Troubleshooting hardware and software, strong customer service skills, networking knowledge, Benefits: Remote work options, flexible hours, professional development opportunities, Salary Range: $45,000 - $55,000."},
    {"role": "user", "content": "Job ID: 24, Position: Research Scientist, Required Skills: Laboratory experience, data analysis, critical thinking abilities, Benefits: Health insurance, retirement plans, paid time off, Salary Range: $80,000 - $95,000."},
    {"role": "user", "content": "Job ID: 25, Position: Restaurant Manager, Required Skills: Leadership abilities, knowledge of restaurant operations, customer service skills, Benefits: Competitive salary, health insurance, performance-based bonuses, Salary Range: $50,000 - $60,000."},
    {"role": "user", "content": "Job ID: 26, Position: Web Developer, Required Skills: Proficiency in HTML, CSS, JavaScript, knowledge of responsive design, Benefits: Flexible working hours, remote work options, professional development budget, Salary Range: $60,000 - $75,000."},
    {"role": "user", "content": "Job ID: 27, Position: Pharmacist, Required Skills: Pharmacy degree, state license, attention to detail, Benefits: Comprehensive healthcare coverage, retirement plans, paid time off, Salary Range: $100,000 - $120,000."},
    {"role": "user", "content": "Job ID: 28, Position: Customer Success Manager, Required Skills: Strong communication skills, customer relationship management, problem-solving abilities, Benefits: Flexible schedule, remote work options, performance-based bonuses, Salary Range: $70,000 - $85,000."},
    {"role": "user", "content": "Job ID: 29, Position: Electrical Engineer, Required Skills: Circuit design, knowledge of electrical codes and regulations, problem-solving abilities, Benefits: Health insurance, retirement plans, professional development opportunities, Salary Range: $80,000 - $95,000."},
    {"role": "user", "content": "Job ID: 30, Position: Senior Marketing Manager, Required Skills: Strategic planning, campaign management, leadership abilities, Benefits: Competitive salary, health and wellness programs, annual performance bonuses, Salary Range: $110,000 - $130,000."},
    {"role": "user", "content": "Job ID: 31, Position: Data Analyst, Required Skills: Proficiency in SQL, data visualization tools, statistical analysis, Benefits: Remote work options, flexible schedule, competitive salary, Salary Range: $70,000 - $85,000."},
    {"role": "user", "content": "Job ID: 32, Position: Healthcare Administrator, Required Skills: Knowledge of healthcare policies and regulations, leadership abilities, budget management, Benefits: Comprehensive healthcare coverage, retirement plans, professional development opportunities, Salary Range: $90,000 - $110,000."},
    {"role": "user", "content": "Job ID: 33, Position: Content Marketing Manager, Required Skills: Content strategy development, SEO knowledge, strong writing skills, Benefits: Remote work options, flexible schedule, performance-based bonuses, Salary Range: $75,000 - $90,000."},
    {"role": "user", "content": "Job ID: 34, Position: Civil Engineer, Required Skills: Proficiency in AutoCAD, knowledge of civil engineering principles, project management abilities, Benefits: Health insurance, retirement plans, professional development opportunities, Salary Range: $80,000 - $95,000."},
    {"role": "user", "content": "Job ID: 35, Position: Human Resources Coordinator, Required Skills: Recruitment and onboarding experience, HRIS knowledge, strong interpersonal skills, Benefits: Paid time off, employee benefits, career advancement opportunities, Salary Range: $50,000 - $60,000."},
    {"role": "user", "content": "Job ID: 36, Position: Data Entry Specialist, Required Skills: Strong attention to detail, fast and accurate typing skills, organizational abilities, Benefits: Competitive salary, paid training, career growth potential, Salary Range: $30,000 - $40,000."},
    {"role": "user", "content": "Job ID: 37, Position: UX/UI Designer, Required Skills: User research, wireframing, proficiency in design tools, Benefits: Flexible working hours, remote work options, professional development budget, Salary Range: $70,000 - $85,000."},
    {"role": "user", "content": "Job ID: 38, Position: Financial Planner, Required Skills: Knowledge of investment strategies, financial analysis, excellent communication skills, Benefits: 401(k) matching, health insurance, professional development opportunities, Salary Range: $80,000 - $100,000."},
    {"role": "user", "content": "Job ID: 39, Position: Operations Analyst, Required Skills: Data analysis, process improvement, strong problem-solving abilities, Benefits: Remote work options, flexible schedule, competitive salary, Salary Range: $60,000 - $75,000."},
    {"role": "user", "content": "Job ID: 40, Position: Physical Therapist, Required Skills: Physical therapy degree, state license, strong clinical skills, Benefits: Comprehensive healthcare coverage, retirement plans, paid time off, Salary Range: $70,000 - $90,000."},
    {"role": "user", "content": "Job ID: 41, Position: Software Quality Assurance Tester, Required Skills: Testing methodologies, bug tracking tools, attention to detail, Benefits: Remote work options, flexible schedule, competitive compensation, Salary Range: $50,000 - $60,000."},
    {"role": "user", "content": "Job ID: 42, Position: Operations Coordinator, Required Skills: Organizational skills, project management abilities, attention to detail, Benefits: Paid time off, healthcare coverage, retirement plans, Salary Range: $40,000 - $50,000."},
    {"role": "user", "content": "Job ID: 43, Position: Event Planner, Required Skills: Strong organizational skills, vendor management, attention to detail, Benefits: Flexible schedule, career development opportunities, company-sponsored events, Salary Range: $45,000 - $55,000."},
    {"role": "user", "content": "Job ID: 44, Position: Mechanical Design Engineer, Required Skills: Proficiency in CAD software, mechanical engineering principles, problem-solving abilities, Benefits: Health insurance, retirement plans, professional development opportunities, Salary Range: $85,000 - $100,000."},
    {"role": "user", "content": "Job ID: 45, Position: Marketing Analyst, Required Skills: Market research, data analysis, proficiency in Excel, Benefits: Remote work options, flexible schedule, competitive salary, Salary Range: $65,000 - $80,000."},
    {"role": "user", "content": "Job ID: 46, Position: Network Administrator, Required Skills: Network troubleshooting, knowledge of network protocols, cybersecurity awareness, Benefits: Remote work options, flexible hours, professional development opportunities, Salary Range: $75,000 - $90,000."},
    {"role": "user", "content": "Job ID: 47, Position: Business Development Manager, Required Skills: Sales experience, market research, negotiation abilities, Benefits: Competitive salary, commission structure, health insurance, Salary Range: $90,000 - $110,000."},
    {"role": "user", "content": "Job ID: 48, Position: Legal Counsel, Required Skills: Knowledge of contract law, strong analytical skills, attention to detail, Benefits: Comprehensive healthcare coverage, retirement plans, professional development opportunities, Salary Range: $100,000 - $120,000."},
    {"role": "user", "content": "Job ID: 49, Position: Supply Chain Analyst, Required Skills: Inventory management, data analysis, supply chain optimization, Benefits: Remote work options, flexible schedule, competitive salary, Salary Range: $70,000 - $85,000."},
    {"role": "user", "content": "Job ID: 50, Position: Occupational Therapist, Required Skills: Occupational therapy degree, state license, strong clinical skills, Benefits: Comprehensive healthcare coverage, retirement plans, paid time off, Salary Range: $75,000 - $90,000."},
    {"role": "user", "content": "Job ID: 51, Position: Product Manager, Required Skills: Product strategy, market research, project management, Benefits: Flexible working hours, remote work options, performance bonuses, Salary Range: $90,000 - $110,000."},
    {"role": "user", "content": "Job ID: 52, Position: Veterinary Technician, Required Skills: Veterinary assistant certification, animal handling skills, medical knowledge, Benefits: Health insurance, retirement plans, professional development opportunities, Salary Range: $35,000 - $45,000."},
    {"role": "user", "content": "Job ID: 53, Position: Business Analyst, Required Skills: Data analysis, requirements gathering, process improvement, Benefits: Remote work options, flexible schedule, competitive salary, Salary Range: $70,000 - $85,000."},
    {"role": "user", "content": "Job ID: 54, Position: Art Director, Required Skills: Creative vision, design leadership, proficiency in design software, Benefits: Remote work options, flexible hours, professional development budget, Salary Range: $80,000 - $95,000."},
    {"role": "user", "content": "Job ID: 55, Position: Construction Project Manager, Required Skills: Project management, budgeting and scheduling, knowledge of construction processes, Benefits: Health insurance, retirement plans, professional development opportunities, Salary Range: $90,000 - $110,000."},
    {"role": "user", "content": "Job ID: 56, Position: Data Engineer, Required Skills: Proficiency in SQL, ETL processes, data modeling, Benefits: Remote work options, flexible schedule, competitive salary, Salary Range: $80,000 - $95,000."},
    {"role": "user", "content": "Job ID: 57, Position: Registered Dietitian, Required Skills: Nutrition degree, state license, counseling skills, Benefits: Comprehensive healthcare coverage, retirement plans, paid time off, Salary Range: $55,000 - $65,000."},
    {"role": "user", "content": "Job ID: 58, Position: Supply Chain Manager, Required Skills: Supply chain optimization, vendor management, logistics coordination, Benefits: Competitive salary, performance-based bonuses, health insurance, Salary Range: $100,000 - $120,000."},
    {"role": "user", "content": "Job ID: 59, Position: IT Project Manager, Required Skills: Project management methodologies, stakeholder communication, technical knowledge, Benefits: Remote work options, flexible hours, professional development opportunities, Salary Range: $95,000 - $115,000."},
    {"role": "user", "content": "Job ID: 60, Position: Research Assistant, Required Skills: Research methods, data collection, attention to detail, Benefits: Health insurance, retirement plans, paid time off, Salary Range: $40,000 - $50,000."},
    {"role": "user", "content": "Job ID: 61, Position: Environmental Scientist, Required Skills: Environmental research, data analysis, knowledge of regulatory frameworks, Benefits: Health insurance, retirement plans, professional development opportunities, Salary Range: $60,000 - $75,000."},
    {"role": "user", "content": "Job ID: 62, Position: Software Product Owner, Required Skills: Agile methodologies, product roadmap development, stakeholder management, Benefits: Flexible working hours, remote work options, performance-based bonuses, Salary Range: $85,000 - $100,000."},
    {"role": "user", "content": "Job ID: 63, Position: Executive Chef, Required Skills: Culinary expertise, menu planning, kitchen management, Benefits: Competitive salary, health insurance, paid vacation, Salary Range: $70,000 - $90,000."},
    {"role": "user", "content": "Job ID: 64, Position: IT Security Analyst, Required Skills: Cybersecurity knowledge, vulnerability assessment, incident response, Benefits: Remote work options, flexible schedule, competitive salary, Salary Range: $80,000 - $95,000."},
    {"role": "user", "content": "Job ID: 65, Position: Art Therapist, Required Skills: Art therapy certification, counseling skills, creativity, Benefits: Comprehensive healthcare coverage, retirement plans, paid time off, Salary Range: $50,000 - $60,000."},
    {"role": "user", "content": "Job ID: 66, Position: Mechanical Technician, Required Skills: Technical knowledge, troubleshooting abilities, familiarity with engineering drawings, Benefits: Paid time off, retirement plans, career advancement opportunities, Salary Range: $45,000 - $55,000."},
    {"role": "user", "content": "Job ID: 67, Position: UX Researcher, Required Skills: User research methods, usability testing, data analysis, Benefits: Remote work options, flexible schedule, competitive salary, Salary Range: $75,000 - $90,000."},
    {"role": "user", "content": "Job ID: 68, Position: Business Intelligence Analyst, Required Skills: Data analysis, data visualization, SQL and BI tools proficiency, Benefits: Flexible working hours, remote work options, professional development budget, Salary Range: $80,000 - $95,000."},
    {"role": "user", "content": "Job ID: 69, Position: Physical Education Teacher, Required Skills: Teaching certification, knowledge of physical education curriculum, communication skills, Benefits: Health insurance, retirement plans, professional development opportunities, Salary Range: $45,000 - $55,000."},
    {"role": "user", "content": "Job ID: 70, Position: E-commerce Manager, Required Skills: E-commerce strategy, digital marketing, data analysis, Benefits: Remote work options, flexible schedule, performance-based bonuses, Salary Range: $70,000 - $85,000."}
]

response_text = generate_chat_completion(messages)
print(response_text)
